### PR TITLE
Moved inline requires on top

### PR DESCRIPTION
**Pull request by thetutlage**

### CODE REVIEW

**Comment by kasperp** [comment]
Thanks for your pull request. I can see how this solves the problem that `require('angular')` returns `undefined`. However the fix assumes that the `require('angular')` statement has a sideeffect of adding `angular` to the global object. I would prefer if the fix was a little more defensive, so what about changing line 12 to:

```javascript
module.exports = factory(require('react'), require('angular') || root['angular']);
```

Would that solve your issue ?

@davidchang any preferences ?

**Comment by thetutlage** [comment]
No it says TypeError: angular.module is not a function

**Comment by thetutlage** [comment]
require('angular') returns an empty object , instead of undefined so we can reverse it like this

```javascript
    module.exports = factory(require('react'),angular || require('angular'));
```
Using global angular if there or require one

**Comment by kasperp** [comment]
@thetutlage I created a pull request to your test repository that works for me. Let me know how you get on.

**Pull request closed without merging**
