### PR TITLE
Added better support for webpack / CommonJS

### PR DESCRIPTION
**Pull request by okonet**
As mentioned in this discussion (https://github.com/davidchang/ngReact/pull/38) this should fix the case then using webpack and angular was already loaded.

`require('angular')` returns an empty object for some reason...

### CODE REVIEW

**Comment by hasdavidc** [comment]
@kasperp would you mind confirming if this is still an issue?

also, should prefer `root.angular` to be safer and avoid a reference error

**Comment by okonet** [comment]
I agree about `root`. I'll make a change.

**Comment by kasperp** [comment]
I didn't know it was an issue, but the purposed fix is nice and simple, so I'm good with merging.

**Comment by okonet** [comment]
Not sure what's going on there, but it doesn't work with root for my setup:

2015-08-17 at 10 23

**Comment by kasperp** [comment]
@okonet there is are some failing tests, is this pull request still relevant?

**Comment by okonet** [comment]
Yes. I'm using it from my fork now. Why are they failing?

**Comment by kasperp** [comment]
check it out her https://travis-ci.org/davidchang/ngReact/builds/75938007

**Comment by okonet** [comment]
Well it seems that 0.10 doesn't support peerDependencies. Not sure you want to support 0.10

**Comment by kasperp** [comment]
No I guess not.

 Would you mind making that change in your PR as well.

@davidchang any thoughts?

**Comment by elliottsj** [comment]
I don't think this PR should be merged; see https://github.com/davidchang/ngReact/pull/113#issuecomment-150306667

If you use [angular >= 1.3.14](https://github.com/angular/angular.js/blob/master/CHANGELOG.md#1314-instantaneous-browserification-2015-02-24), the CommonJS entry point should return the angular instance for you:

**Comment by okonet** [comment]
@elliottsj it's not working with webpack without it for some reason

**Comment by elliottsj** [comment]
@okonet Are you using angular >= 1.3.14? I believe older versions did not export the `angular` value.

If you're using an older version, I'd recommend using [exports-loader](https://github.com/webpack/exports-loader):
```js
var angular = require('exports?window.angular!angular');
```

**Comment by kasperp** [comment]
closed in favor for #113

**Pull request closed without merging**
