### PR TITLE
Add example of how to write unit tests along with how to use babel and webpack

### PR DESCRIPTION
**Pull request by zpratt**
The included example is meant to be self-contained. That's why it includes its own `package.json` and `.gitignore`.

### CODE REVIEW

**Comment by kasperp** [comment]
Wow - that is awesome, thanks a lot for doing that. We have really been missing an example like that. 

Let me look through your example a little more carefully - thanks.

**Comment by zpratt** [comment]
Any thoughts on this? Can I make it better?

**Comment by kasperp** [comment]
No I think it looks really good. 

Only little annoying nitpic is that the rest of the code in `ngReact`is indented with 2 spaces, yours is with 4 :smile_cat: I can merge your pull request and change it or you can do it - what do you think?

Thanks again.

**Comment by zpratt** [comment]
@kasperp no problem. I've added an editorconfig file to make it easy to do the right thing and I've formatted all the js files with 2 spaces.

**Comment by kasperp** [comment]
Perfect - thanks for the effort.

**Pull request merged**
