### PR TITLE
Callback and data

### PR DESCRIPTION
**Pull request by kasperp**
fix for #78, closes #79.

@psalaets, @javiercr here is an attempt at fixing #78. Would you mind verifying that it solves your issue?

### CODE REVIEW

**Comment by psalaets** [comment]
This fixed it for me

**Comment by javiercr** [comment]
@kasperp this also fixes the issue for me, thanks! :D

**Comment by joemcbride** [comment]
Was also having this issue.  Any chance for an npm push?  Thanks!

**Comment by kasperp** [comment]
@joemcbride we'll do a npm push soon

**Comment by joemcbride** [comment]
:clap: Will be nice to have this plus the watch group pushed.

**Comment by kasperp** [comment]
@davidchang :smile:

**Comment by hasdavidc** [comment]
@javiercr @joemcbride @psalaets @kasperp my apologies for the delay - 0.1.6 is released: https://github.com/davidchang/ngReact/releases/tag/0.1.6 (thanks @psalaets for the issue and writing failing tests! Thanks Kasper as always :D )

**Pull request merged**
