### PR TITLE
Safe apply when wrapping functions

### PR DESCRIPTION
**Pull request by Fjandin**
Had some cases where i needed to pass a method to a component. This method would run inside an angular that is (ofcourse) already inside an apply. This change makes sure that we are only wrapping the function in scope.apply if we are outside the scope.

### CODE REVIEW

**Comment by kasperp** [comment]
Looks good - thanks. 

@davidchang any comments ?

**Comment by kasperp** [comment]
@Fjandin sorry I didn't get back sooner. Do you think it would be possible to add a test case that detects that the function only get wrapped once ?

**Comment by Fjandin** [comment]
Hi. Yes, I shall look into adding a test

**Comment by Fjandin** [comment]
TBH not sure how to test for this, but on the other hand i added a test for the new feature i added. Just makes sure that angular does not throw an exception when running a prop callback inside a scope apply.

**Comment by kasperp** [comment]
Awesome.

**Pull request merged**
