### PR TITLE
Debounce React.render

### PR DESCRIPTION
**Pull request by ethul**
I was looking into the call to [React.render](https://github.com/davidchang/ngReact/blob/a8b95802d7a28a63aa4130bcc82a081ecd349578/ngReact.js#L113) and noticed that for a given react component, the function may be run multiple times.

I am unsure if this is problematic or not, but I was thinking of a way to debounce this to only have the render function be called once. I've put together this PR mainly for discussion and to brainstorm ideas, but it outlines what I had in mind. Granted, maybe this is not an issue at all and not worth changing, but I wanted to bring it up nonetheless.

It basically prevents the reactComponent and reactDirective from calling React.render multiple times before the function has a chance to complete. For example, if the reactDirective invokes a render, and then before that render is complete a second call to render is invoked, the timeout will be cancelled and the new render call will begin.

What do you think? I am definitely open to any comments or suggestions on this.

### CODE REVIEW

**Comment by kasperp** [comment]
@ethul thanks for your pull request. 

I'm also not sure if this is a problem or not. I would like to understand it a little more, would it be possible to write a test that illustrates how React.render is called multiple times ?

**Comment by ethul** [comment]
Welcome. I was thinking about incorporating a test case. I will take a look.

**Comment by ethul** [comment]
I've added test cases in ethul/ngReact#46fd705e865b22a029c7542dda401bfe6dd8eacd and for some reason github did not sync that with this PR.

That aside, I believe the additional render calls are the result of angular initializing a watch listener for each react prop. It could be that a better approach here is to add an option to prevent the render from being called in the watchProps function when the old and new values are identical, as mentioned in the [$watch docs](https://code.angularjs.org/1.3.15/docs/api/ng/type/$rootScope.Scope).

**Comment by ethul** [comment]
Link update [ethul/ngReact#46fd705e865b22a029c7542dda401bfe6dd8eacd](https://github.com/ethul/ngReact/commit/46fd705e865b22a029c7542dda401bfe6dd8eacd)

**Comment by kasperp** [comment]
@ethul thanks for writing the tests. 

> ... I believe the additional render calls are the result of angular initializing a watch listener for each react prop. It could be that a better approach here is to add an option to prevent the render from being called in the watchProps function when the old and new values are identical ..

That sounds right and I do think it would be a better approach to check that new and old values differs before calling React.render. I would prefer this solution over the cache.

**Comment by ethul** [comment]
Agreed. I will open a fresh PR for this.

Do you think this should be opt-in with an attribute? Maybe something like `watch-no-init`?

**Comment by kasperp** [comment]
cool. 

Nah I don't think an extra option is necessary. Would there be any reason for wanting the double render functionality ?

**Comment by ethul** [comment]
Sounds good. No extra option then. I can't really think of a compelling reason to have it.

**Comment by ethul** [comment]
Closing in favor of #57

**Pull request closed without merging**
