### PR TITLE
adds possibility to load namespaced component

### PR DESCRIPTION
**Pull request by matthieu-ravey**
Adds the possibility to load react component like Views.MyComponent

### CODE REVIEW

**Comment by hasdavidc** [comment]
@matthieu-ravey - First off, many thanks for your contribution!

Second, using reduce like that is AWESOME. In my opinion, a really elegant solution (and something I've never seen or realized before).

Only one thing - could you add unit tests?

@kasperp - could you also take a quick look?

**Comment by kasperp** [comment]
Yeah it looks great - thanks. I was just about to ask about adding a test :smile:

**Comment by matthieu-ravey** [comment]
@hasdavidc @kasperp done !

**Comment by kasperp** [comment]
LGTM - thanks again

**Comment by hasdavidc** [comment]
Merging, thanks again for the contribution. I'll make sure to add you to the Contributors list and will make a new release to npm/bower sometime this weekend

**Pull request merged**
