### PR TITLE
Upgrade To React 14

### PR DESCRIPTION
**Pull request by aabenoja**
Also using the `react-addons-test-utils` package now that `react-addons` has been split.

### CODE REVIEW

**Comment by jjstrat3** [comment]
:+1:

**Comment by kasperp** [comment]
Looks great :+1:, thanks pushing for this. I wonder if it worth to provide any backwards-compatibility. Wouldn't it be rather simple with something like

```
ReactDOM = ReactDOM || React; 
```
but I'm unsure if it something that would be useful? 

Also we recently merged #108 we should make those tests stil runs.

**Comment by aabenoja** [comment]
I forgot about those examples. I'll update those shortly.

As for the backwards compatibility I really don't know how to go about defining that in the `package.json` file. Regardless, I don't think it's something to worry about. If a user upgrades to `react@0.14.x` and continues to use `ngReact@0.1.7` they'll be hit with react's deprecation errors warnings around what's being moved.

**Comment by kasperp** [comment]
>I don't think it's something to worry about

Yeah you are probably right

**Comment by yordis** [comment]
:+1:

**Comment by segalr3** [comment]
when is it going to be merged?

**Comment by kasperp** [comment]
My plan was to merge it when the examples also was upgraded. 

After that we need @davidchang to make a new release

**Comment by aabenoja** [comment]
Apologies, I've been swamped. I'll be able to address the examples in a couple of hours.

**Comment by kasperp** [comment]
@aabenoja thanks for the effort.

**Comment by aabenoja** [comment]
@kasperp Now that I think about it, this would probably warrant a minor version bump, would it not? If so, I'll need to make a quick update to the example's `package.json` to point to the would-be `ngReact`.

**Comment by kasperp** [comment]
No I think we have normal ly done the version bump when we publish a new release to npm.

**Comment by elliottsj** [comment]
@kasperp Do you know when the next release will be published?

**Pull request merged**
