### PR TITLE
Use global instance of angular if is available, otherwise require() it.

### PR DESCRIPTION
**Pull request by arnostpleskot**
Hi! This smal fix helps when you use some building tool which provides angular globally (in my case webpack) and require returns only empty object.

I think I saw similar fix around here, but it probably got missing in following commits.

### CODE REVIEW

**Comment by elliottsj** [comment]
I don't think this is needed; if you're using webpack/browserify, `require('angular')` should always return the global angular instance anyway. This is the entry point for angular@1.4.7:

```js
// node_modules/angular/index.js
require('./angular');
module.exports = angular;
```

**Comment by okonet** [comment]
Duplicate of #95

**Comment by kasperp** [comment]
@elliottsj does it hurt anyone? Since this has now been proposed twice it seems to be a real problem in certain setups. 

I would think that it could be solved in webpack with something like the [expose-loader](https://github.com/webpack/expose-loader) and similar for browserify. Having said that I dont' mind merging it if it does hurt anyone.

**Comment by kasperp** [comment]
@okonet this pr passes the test as it doesn't change to peerDependencies. Would you mind if I close #95  in faivor of this one. We can make the change to peerDependencies seperately.

**Comment by elliottsj** [comment]
@kasperp It probably won't hurt in most cases, but I can think of a couple edge cases:

1. if you're running ngReact on Node.js, `angular` will initially be undefined, so you'll get
  ```
  ReferenceError: angular is not defined
  ```

2. Someone might also want to do
  ```js
  delete require.cache[require.resolve('angular')]
  ```
  so that `require('angular')` re-executes the module, but ngReact will just continue using the global `angular` value instead.

The only valid reason I can think of for doing `angular || require('angular')` is to support angular < 1.3.14, but it's better practice (at least with webpack) to use exports-loader instead: https://github.com/davidchang/ngReact/pull/95#issuecomment-150317110

**Comment by kasperp** [comment]
> The only valid reason I can think of for doing angular || require('angular') is to support angular < 1.3.14, but it's better practice (at least with webpack) to use exports-loader instead

Yeah I kind of agree with this. Perhaps a section in the README would prevent people from running into this problem.

@arnostpleskot and @okonet would mind checking if the exports-loader solves your problem.  And what do you think about closing this and adding a section about the exports-loader in the README ?

**Comment by okonet** [comment]
Well, it is not. I don't know why it is not working how it suppose to work. Yes, I use 1.4.x and I have tried expose-loader and other ways of shining angular without any luck. I also don't mind merging this one instead of mine pr. 

I also don't get how can you run angular in node since its browser dependent by design and requires document.

**Comment by elliottsj** [comment]
@okonet I think it's [exports-loader](https://www.npmjs.com/package/exports-loader) that you want (expose-loader exposes a value to the global scope instead of exporting it). Angular 1.4.x should just work though.

If you try bundling this with webpack, what happens?
```js
var angular = require('angular')
console.log(angular.version)
```
It should output an object like `{full: "1.4.7", major: 1, minor: 4, dot: 7, codeName: "dark-luminescence"}`

It's possible to run angular on node using [jsdom](https://github.com/tmpvar/jsdom) :smile:

**Comment by arnostpleskot** [comment]
@elliottsj I'm using exports-loader in combination with [webpack.ProvidePlugin](https://webpack.github.io/docs/list-of-plugins.html#provideplugin). But `require('angular')` returns only empty object.

This is part of my webpack.config.js with exported angular (1.4.7 in my case)
```javascript
new webpack.ProvidePlugin({
    'angular': 'exports?window.angular!angular'
})
```

I'm not sure, but is it possible that require of angular will cause circular dependency?

**Comment by elliottsj** [comment]
@arnostpleskot You'll need to configure it in the `module.loaders` section of your webpack config like this:
```js
module: {
  loaders: [
    {
      test: path.resolve(__dirname, 'node_modules/angular/index.js'),
      loader: 'exports?window.angular'
    }
  ]
}
```

I don't think you need ProvidePlugin.

**Comment by arnostpleskot** [comment]
Ok, I tried these 4 setups:

1) Without use of exports-loader at all
```javascript
console.log(angular);  // returns "undefined"
console.log(window.angular); // returns "undefined"
var angular = require('angular');  
console.log(angular); // returns empty object
console.log(window.angular); // returns angular object
```

2) Exports-loader inside `module.loaders`
```javascript
console.log(angular);  // returns "undefined"
console.log(window.angular); // returns "undefined"
var angular = require('angular');  
console.log(angular); // returns empty object
console.log(window.angular); // returns angular object
```

3) Direct require with exports-loader as is in [readme](https://github.com/webpack/exports-loader)
```javascript
console.log(angular);  // returns "undefined"
console.log(window.angular); // returns "undefined"
var angular = require("exports?angular!../node_modules/angular/index.js");
console.log(angular); // returns angular object
console.log(window.angular); // returns angular object
```

4) My old setup with exports-loader within ProvidePlugin
```javascript
console.log(angular);  // returns angular object
console.log(window.angular); // returns angular object
var angular = require('angular');  // throws "WARNING: Tried to load angular more than once."
console.log(angular); // returns empty object
console.log(window.angular); // returns angular object
```

As I see it, if I want use exports-loader without provide plugin, I need to use it in `require("angular")` directly in ngReact library.  Otherwise for use with webpack I need look for angular in `window.angular` or use my pr with providePlugin (and it works for me for all other modules I use).

**Comment by elliottsj** [comment]
@arnostpleskot I threw together an example project to see what works: https://github.com/elliottsj/angular-exports-loader-example

Turns out it needs to be
```js
path.resolve(__dirname, 'node_modules/angular/angular.js')
```
instead of
```js
path.resolve(__dirname, 'node_modules/angular/index.js')
```

Now it seems to work :smile:

**Comment by kasperp** [comment]
What should we conclude from this? 

I want the package to be as available and easy to use a possible. Should we merge this even if there is a "better practice" around it or should we add a section to the README with what @arnostpleskot is suggesting?

**Comment by elliottsj** [comment]
I would opt for a hint in the README. See #115

**Comment by kasperp** [comment]
Awesome, thanks for the pull request. 

@arnostpleskot and @okonet would like to hear from you, does the proposed fix works for you?

**Comment by arnostpleskot** [comment]
@elliottsj, thanks, your example works fine for me. 

@kasperp I'm for use #115 and close this one.

**Comment by okonet** [comment]
I'm also for not changing module definition part of the proposed solution works. Still need to try it out though.

**Comment by kasperp** [comment]
thanks for your contributions - I'll merge #115 and close this one.

**Pull request closed without merging**
